/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppMcpRouteImport } from './routes/app.mcp'
import { Route as AppDocsRouteImport } from './routes/app.docs'
import { Route as AppConnectionsRouteImport } from './routes/app.connections'
import { Route as AppBrainRouteImport } from './routes/app.brain'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AppTeamIdRouteImport } from './routes/app.team.$id'
import { Route as AppAgentsNewRouteImport } from './routes/app.agents.new'
import { Route as AppAgentsIdRouteImport } from './routes/app.agents.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpRoute = AppMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppBrainRoute = AppBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamIdRoute = AppTeamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppAgentsNewRoute = AppAgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAgentsRoute,
} as any)
const AppAgentsIdRoute = AppAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/brain': typeof AppBrainRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/mcp': typeof AppMcpRoute
  '/app/team': typeof AppTeamRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/agents/new': typeof AppAgentsNewRoute
  '/app/team/$id': typeof AppTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/brain': typeof AppBrainRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/mcp': typeof AppMcpRoute
  '/app/team': typeof AppTeamRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/agents/new': typeof AppAgentsNewRoute
  '/app/team/$id': typeof AppTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/brain': typeof AppBrainRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/mcp': typeof AppMcpRoute
  '/app/team': typeof AppTeamRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/agents/new': typeof AppAgentsNewRoute
  '/app/team/$id': typeof AppTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/api/chat'
    | '/app/agents'
    | '/app/approvals'
    | '/app/brain'
    | '/app/connections'
    | '/app/docs'
    | '/app/mcp'
    | '/app/team'
    | '/app/'
    | '/app/agents/$id'
    | '/app/agents/new'
    | '/app/team/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/app/agents'
    | '/app/approvals'
    | '/app/brain'
    | '/app/connections'
    | '/app/docs'
    | '/app/mcp'
    | '/app/team'
    | '/app'
    | '/app/agents/$id'
    | '/app/agents/new'
    | '/app/team/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/api/chat'
    | '/app/agents'
    | '/app/approvals'
    | '/app/brain'
    | '/app/connections'
    | '/app/docs'
    | '/app/mcp'
    | '/app/team'
    | '/app/'
    | '/app/agents/$id'
    | '/app/agents/new'
    | '/app/team/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mcp': {
      id: '/app/mcp'
      path: '/mcp'
      fullPath: '/app/mcp'
      preLoaderRoute: typeof AppMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections': {
      id: '/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brain': {
      id: '/app/brain'
      path: '/brain'
      fullPath: '/app/brain'
      preLoaderRoute: typeof AppBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team/$id': {
      id: '/app/team/$id'
      path: '/$id'
      fullPath: '/app/team/$id'
      preLoaderRoute: typeof AppTeamIdRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/app/agents/new': {
      id: '/app/agents/new'
      path: '/new'
      fullPath: '/app/agents/new'
      preLoaderRoute: typeof AppAgentsNewRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/app/agents/$id': {
      id: '/app/agents/$id'
      path: '/$id'
      fullPath: '/app/agents/$id'
      preLoaderRoute: typeof AppAgentsIdRouteImport
      parentRoute: typeof AppAgentsRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsIdRoute: typeof AppAgentsIdRoute
  AppAgentsNewRoute: typeof AppAgentsNewRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsIdRoute: AppAgentsIdRoute,
  AppAgentsNewRoute: AppAgentsNewRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppTeamRouteChildren {
  AppTeamIdRoute: typeof AppTeamIdRoute
}

const AppTeamRouteChildren: AppTeamRouteChildren = {
  AppTeamIdRoute: AppTeamIdRoute,
}

const AppTeamRouteWithChildren =
  AppTeamRoute._addFileChildren(AppTeamRouteChildren)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppBrainRoute: typeof AppBrainRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppDocsRoute: typeof AppDocsRoute
  AppMcpRoute: typeof AppMcpRoute
  AppTeamRoute: typeof AppTeamRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppApprovalsRoute: AppApprovalsRoute,
  AppBrainRoute: AppBrainRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppDocsRoute: AppDocsRoute,
  AppMcpRoute: AppMcpRoute,
  AppTeamRoute: AppTeamRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
