/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsExamplesRouteImport } from './routes/docs.examples'
import { Route as DocsBuildingToolsRouteImport } from './routes/docs.building-tools'
import { Route as DocsApprovalsRouteImport } from './routes/docs.approvals'
import { Route as DocsAgentsRouteImport } from './routes/docs.agents'
import { Route as DocsActivityLogsRouteImport } from './routes/docs.activity-logs'
import { Route as DocsAccessKeysRouteImport } from './routes/docs.access-keys'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppKeysRouteImport } from './routes/app.keys'
import { Route as AppDocsRouteImport } from './routes/app.docs'
import { Route as AppConnectionsRouteImport } from './routes/app.connections'
import { Route as AppBuildsRouteImport } from './routes/app.builds'
import { Route as AppBrainRouteImport } from './routes/app.brain'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as DocsCliOpencodeRouteImport } from './routes/docs.cli.opencode'
import { Route as DocsCliCursorRouteImport } from './routes/docs.cli.cursor'
import { Route as DocsCliClaudeCodeRouteImport } from './routes/docs.cli.claude-code'
import { Route as DocsBuildingToolsCustomerHealthDashboardRouteImport } from './routes/docs.building-tools.customer-health-dashboard'
import { Route as AppTeamIdRouteImport } from './routes/app.team.$id'
import { Route as AppKeysIdRouteImport } from './routes/app.keys.$id'
import { Route as AppAgentsNewRouteImport } from './routes/app.agents.new'
import { Route as AppAgentsIdRouteImport } from './routes/app.agents.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/docs/quickstart',
  path: '/docs/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: '/docs/examples',
  path: '/docs/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsBuildingToolsRoute = DocsBuildingToolsRouteImport.update({
  id: '/docs/building-tools',
  path: '/docs/building-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApprovalsRoute = DocsApprovalsRouteImport.update({
  id: '/docs/approvals',
  path: '/docs/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAgentsRoute = DocsAgentsRouteImport.update({
  id: '/docs/agents',
  path: '/docs/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsActivityLogsRoute = DocsActivityLogsRouteImport.update({
  id: '/docs/activity-logs',
  path: '/docs/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAccessKeysRoute = DocsAccessKeysRouteImport.update({
  id: '/docs/access-keys',
  path: '/docs/access-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildsRoute = AppBuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => AppRoute,
} as any)
const AppBrainRoute = AppBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliOpencodeRoute = DocsCliOpencodeRouteImport.update({
  id: '/docs/cli/opencode',
  path: '/docs/cli/opencode',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliCursorRoute = DocsCliCursorRouteImport.update({
  id: '/docs/cli/cursor',
  path: '/docs/cli/cursor',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliClaudeCodeRoute = DocsCliClaudeCodeRouteImport.update({
  id: '/docs/cli/claude-code',
  path: '/docs/cli/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsBuildingToolsCustomerHealthDashboardRoute =
  DocsBuildingToolsCustomerHealthDashboardRouteImport.update({
    id: '/customer-health-dashboard',
    path: '/customer-health-dashboard',
    getParentRoute: () => DocsBuildingToolsRoute,
  } as any)
const AppTeamIdRoute = AppTeamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppKeysIdRoute = AppKeysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppKeysRoute,
} as any)
const AppAgentsNewRoute = AppAgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAgentsRoute,
} as any)
const AppAgentsIdRoute = AppAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/brain': typeof AppBrainRoute
  '/app/builds': typeof AppBuildsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/keys': typeof AppKeysRouteWithChildren
  '/app/team': typeof AppTeamRouteWithChildren
  '/docs/access-keys': typeof DocsAccessKeysRoute
  '/docs/activity-logs': typeof DocsActivityLogsRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/approvals': typeof DocsApprovalsRoute
  '/docs/building-tools': typeof DocsBuildingToolsRouteWithChildren
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/agents/new': typeof AppAgentsNewRoute
  '/app/keys/$id': typeof AppKeysIdRoute
  '/app/team/$id': typeof AppTeamIdRoute
  '/docs/building-tools/customer-health-dashboard': typeof DocsBuildingToolsCustomerHealthDashboardRoute
  '/docs/cli/claude-code': typeof DocsCliClaudeCodeRoute
  '/docs/cli/cursor': typeof DocsCliCursorRoute
  '/docs/cli/opencode': typeof DocsCliOpencodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/brain': typeof AppBrainRoute
  '/app/builds': typeof AppBuildsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/keys': typeof AppKeysRouteWithChildren
  '/app/team': typeof AppTeamRouteWithChildren
  '/docs/access-keys': typeof DocsAccessKeysRoute
  '/docs/activity-logs': typeof DocsActivityLogsRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/approvals': typeof DocsApprovalsRoute
  '/docs/building-tools': typeof DocsBuildingToolsRouteWithChildren
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/app': typeof AppIndexRoute
  '/docs': typeof DocsIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/agents/new': typeof AppAgentsNewRoute
  '/app/keys/$id': typeof AppKeysIdRoute
  '/app/team/$id': typeof AppTeamIdRoute
  '/docs/building-tools/customer-health-dashboard': typeof DocsBuildingToolsCustomerHealthDashboardRoute
  '/docs/cli/claude-code': typeof DocsCliClaudeCodeRoute
  '/docs/cli/cursor': typeof DocsCliCursorRoute
  '/docs/cli/opencode': typeof DocsCliOpencodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/brain': typeof AppBrainRoute
  '/app/builds': typeof AppBuildsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/keys': typeof AppKeysRouteWithChildren
  '/app/team': typeof AppTeamRouteWithChildren
  '/docs/access-keys': typeof DocsAccessKeysRoute
  '/docs/activity-logs': typeof DocsActivityLogsRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/approvals': typeof DocsApprovalsRoute
  '/docs/building-tools': typeof DocsBuildingToolsRouteWithChildren
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
  '/app/agents/new': typeof AppAgentsNewRoute
  '/app/keys/$id': typeof AppKeysIdRoute
  '/app/team/$id': typeof AppTeamIdRoute
  '/docs/building-tools/customer-health-dashboard': typeof DocsBuildingToolsCustomerHealthDashboardRoute
  '/docs/cli/claude-code': typeof DocsCliClaudeCodeRoute
  '/docs/cli/cursor': typeof DocsCliCursorRoute
  '/docs/cli/opencode': typeof DocsCliOpencodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/api/chat'
    | '/app/agents'
    | '/app/approvals'
    | '/app/brain'
    | '/app/builds'
    | '/app/connections'
    | '/app/docs'
    | '/app/keys'
    | '/app/team'
    | '/docs/access-keys'
    | '/docs/activity-logs'
    | '/docs/agents'
    | '/docs/approvals'
    | '/docs/building-tools'
    | '/docs/examples'
    | '/docs/quickstart'
    | '/app/'
    | '/docs/'
    | '/app/agents/$id'
    | '/app/agents/new'
    | '/app/keys/$id'
    | '/app/team/$id'
    | '/docs/building-tools/customer-health-dashboard'
    | '/docs/cli/claude-code'
    | '/docs/cli/cursor'
    | '/docs/cli/opencode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/app/agents'
    | '/app/approvals'
    | '/app/brain'
    | '/app/builds'
    | '/app/connections'
    | '/app/docs'
    | '/app/keys'
    | '/app/team'
    | '/docs/access-keys'
    | '/docs/activity-logs'
    | '/docs/agents'
    | '/docs/approvals'
    | '/docs/building-tools'
    | '/docs/examples'
    | '/docs/quickstart'
    | '/app'
    | '/docs'
    | '/app/agents/$id'
    | '/app/agents/new'
    | '/app/keys/$id'
    | '/app/team/$id'
    | '/docs/building-tools/customer-health-dashboard'
    | '/docs/cli/claude-code'
    | '/docs/cli/cursor'
    | '/docs/cli/opencode'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/api/chat'
    | '/app/agents'
    | '/app/approvals'
    | '/app/brain'
    | '/app/builds'
    | '/app/connections'
    | '/app/docs'
    | '/app/keys'
    | '/app/team'
    | '/docs/access-keys'
    | '/docs/activity-logs'
    | '/docs/agents'
    | '/docs/approvals'
    | '/docs/building-tools'
    | '/docs/examples'
    | '/docs/quickstart'
    | '/app/'
    | '/docs/'
    | '/app/agents/$id'
    | '/app/agents/new'
    | '/app/keys/$id'
    | '/app/team/$id'
    | '/docs/building-tools/customer-health-dashboard'
    | '/docs/cli/claude-code'
    | '/docs/cli/cursor'
    | '/docs/cli/opencode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  DocsAccessKeysRoute: typeof DocsAccessKeysRoute
  DocsActivityLogsRoute: typeof DocsActivityLogsRoute
  DocsAgentsRoute: typeof DocsAgentsRoute
  DocsApprovalsRoute: typeof DocsApprovalsRoute
  DocsBuildingToolsRoute: typeof DocsBuildingToolsRouteWithChildren
  DocsExamplesRoute: typeof DocsExamplesRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsCliClaudeCodeRoute: typeof DocsCliClaudeCodeRoute
  DocsCliCursorRoute: typeof DocsCliCursorRoute
  DocsCliOpencodeRoute: typeof DocsCliOpencodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/docs/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/examples': {
      id: '/docs/examples'
      path: '/docs/examples'
      fullPath: '/docs/examples'
      preLoaderRoute: typeof DocsExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/building-tools': {
      id: '/docs/building-tools'
      path: '/docs/building-tools'
      fullPath: '/docs/building-tools'
      preLoaderRoute: typeof DocsBuildingToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/approvals': {
      id: '/docs/approvals'
      path: '/docs/approvals'
      fullPath: '/docs/approvals'
      preLoaderRoute: typeof DocsApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/agents': {
      id: '/docs/agents'
      path: '/docs/agents'
      fullPath: '/docs/agents'
      preLoaderRoute: typeof DocsAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/activity-logs': {
      id: '/docs/activity-logs'
      path: '/docs/activity-logs'
      fullPath: '/docs/activity-logs'
      preLoaderRoute: typeof DocsActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/access-keys': {
      id: '/docs/access-keys'
      path: '/docs/access-keys'
      fullPath: '/docs/access-keys'
      preLoaderRoute: typeof DocsAccessKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/keys': {
      id: '/app/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections': {
      id: '/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/builds': {
      id: '/app/builds'
      path: '/builds'
      fullPath: '/app/builds'
      preLoaderRoute: typeof AppBuildsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brain': {
      id: '/app/brain'
      path: '/brain'
      fullPath: '/app/brain'
      preLoaderRoute: typeof AppBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli/opencode': {
      id: '/docs/cli/opencode'
      path: '/docs/cli/opencode'
      fullPath: '/docs/cli/opencode'
      preLoaderRoute: typeof DocsCliOpencodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli/cursor': {
      id: '/docs/cli/cursor'
      path: '/docs/cli/cursor'
      fullPath: '/docs/cli/cursor'
      preLoaderRoute: typeof DocsCliCursorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli/claude-code': {
      id: '/docs/cli/claude-code'
      path: '/docs/cli/claude-code'
      fullPath: '/docs/cli/claude-code'
      preLoaderRoute: typeof DocsCliClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/building-tools/customer-health-dashboard': {
      id: '/docs/building-tools/customer-health-dashboard'
      path: '/customer-health-dashboard'
      fullPath: '/docs/building-tools/customer-health-dashboard'
      preLoaderRoute: typeof DocsBuildingToolsCustomerHealthDashboardRouteImport
      parentRoute: typeof DocsBuildingToolsRoute
    }
    '/app/team/$id': {
      id: '/app/team/$id'
      path: '/$id'
      fullPath: '/app/team/$id'
      preLoaderRoute: typeof AppTeamIdRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/app/keys/$id': {
      id: '/app/keys/$id'
      path: '/$id'
      fullPath: '/app/keys/$id'
      preLoaderRoute: typeof AppKeysIdRouteImport
      parentRoute: typeof AppKeysRoute
    }
    '/app/agents/new': {
      id: '/app/agents/new'
      path: '/new'
      fullPath: '/app/agents/new'
      preLoaderRoute: typeof AppAgentsNewRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/app/agents/$id': {
      id: '/app/agents/$id'
      path: '/$id'
      fullPath: '/app/agents/$id'
      preLoaderRoute: typeof AppAgentsIdRouteImport
      parentRoute: typeof AppAgentsRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsIdRoute: typeof AppAgentsIdRoute
  AppAgentsNewRoute: typeof AppAgentsNewRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsIdRoute: AppAgentsIdRoute,
  AppAgentsNewRoute: AppAgentsNewRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppKeysRouteChildren {
  AppKeysIdRoute: typeof AppKeysIdRoute
}

const AppKeysRouteChildren: AppKeysRouteChildren = {
  AppKeysIdRoute: AppKeysIdRoute,
}

const AppKeysRouteWithChildren =
  AppKeysRoute._addFileChildren(AppKeysRouteChildren)

interface AppTeamRouteChildren {
  AppTeamIdRoute: typeof AppTeamIdRoute
}

const AppTeamRouteChildren: AppTeamRouteChildren = {
  AppTeamIdRoute: AppTeamIdRoute,
}

const AppTeamRouteWithChildren =
  AppTeamRoute._addFileChildren(AppTeamRouteChildren)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppBrainRoute: typeof AppBrainRoute
  AppBuildsRoute: typeof AppBuildsRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppDocsRoute: typeof AppDocsRoute
  AppKeysRoute: typeof AppKeysRouteWithChildren
  AppTeamRoute: typeof AppTeamRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppApprovalsRoute: AppApprovalsRoute,
  AppBrainRoute: AppBrainRoute,
  AppBuildsRoute: AppBuildsRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppDocsRoute: AppDocsRoute,
  AppKeysRoute: AppKeysRouteWithChildren,
  AppTeamRoute: AppTeamRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DocsBuildingToolsRouteChildren {
  DocsBuildingToolsCustomerHealthDashboardRoute: typeof DocsBuildingToolsCustomerHealthDashboardRoute
}

const DocsBuildingToolsRouteChildren: DocsBuildingToolsRouteChildren = {
  DocsBuildingToolsCustomerHealthDashboardRoute:
    DocsBuildingToolsCustomerHealthDashboardRoute,
}

const DocsBuildingToolsRouteWithChildren =
  DocsBuildingToolsRoute._addFileChildren(DocsBuildingToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  DocsAccessKeysRoute: DocsAccessKeysRoute,
  DocsActivityLogsRoute: DocsActivityLogsRoute,
  DocsAgentsRoute: DocsAgentsRoute,
  DocsApprovalsRoute: DocsApprovalsRoute,
  DocsBuildingToolsRoute: DocsBuildingToolsRouteWithChildren,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsCliClaudeCodeRoute: DocsCliClaudeCodeRoute,
  DocsCliCursorRoute: DocsCliCursorRoute,
  DocsCliOpencodeRoute: DocsCliOpencodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
